# Generated by Django 5.1.1 on 2024-09-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='NoNameTask', max_length=150, verbose_name='Название задачи')),
                ('task_desc', models.CharField(default='No descriptions', max_length=512, verbose_name='Описание задачи')),
                ('task_complited', models.BooleanField(verbose_name='Задача выполнена')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
